import { Comic, UserAccount, CommentItem } from '../types';

export const INITIAL_COMICS: Comic[] = [
  {
    id: 'comic-secret-stepmother',
    title: 'Secret Stepmother: Room Next Door',
    slug: 'secret-stepmother-room-next-door',
    coverImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop',
    synopsis: 'Min-Woo tinggal bersebelahan dengan ibu tirinya yang mempesona setelah ayahnya pergi ke luar negeri. Hubungan terlarang dan penuh ketegangan pun mulai terjalin di balik pintu kamar yang selalu tertutup rapat.',
    storyWriter: 'Kim Min-Woo',
    artist: 'Park Jin-Ah',
    rating: 4.9,
    ratingCount: 18450,
    genres: ['Romance 18+', 'Drama Dewasa', 'Milf / Noona', 'Harem', 'Webtoon'],
    type: 'manhwa',
    contentRating: '18plus',
    status: 'Ongoing',
    totalChapters: 45,
    totalViews: 342000,
    showOnHome: true,
    isFeatured: true,
    isTrending: true,
    createdAt: '2025-01-10T12:00:00Z',
    updatedAt: '2025-02-18T10:00:00Z',
  },
  {
    id: 'comic-silent-war',
    title: 'Silent War: Special Relations',
    slug: 'silent-war-special-relations',
    coverImage: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop',
    synopsis: 'Kisah seorang pemuda yang menemukan rahasia tergelap di balik apartemen mewahnya dan bagaimana ia memanfaatkannya untuk membalas dendam.',
    storyWriter: 'Yoon Se-Jin',
    artist: 'Kang Do-Hoon',
    rating: 4.8,
    ratingCount: 12890,
    genres: ['Drama Dewasa', 'Romance 18+', 'Psychological', 'Revenge'],
    type: 'manhwa',
    contentRating: '18plus',
    status: 'Completed',
    totalChapters: 120,
    totalViews: 580000,
    showOnHome: true,
    isFeatured: false,
    isTrending: true,
    createdAt: '2024-11-05T08:00:00Z',
    updatedAt: '2025-01-20T14:30:00Z',
  },
  {
    id: 'comic-boarding-diary',
    title: 'Boarding Diary (Buku Harian Kos)',
    slug: 'boarding-diary',
    coverImage: 'https://images.unsplash.com/photo-1544717305-2782549b5136?q=80&w=800&auto=format&fit=crop',
    synopsis: 'Jun-Woo pindah ke rumah kos teman ibunya untuk kuliah. Namun suasana rumah kos ini ternyata jauh lebih menggoda daripada yang ia bayangkan.',
    storyWriter: 'Lee Tae-Ho',
    artist: 'Son Ga-Ram',
    rating: 4.95,
    ratingCount: 29400,
    genres: ['Romance 18+', 'Milf / Noona', 'Campus Life', 'Comedy'],
    type: 'manhwa',
    contentRating: '18plus',
    status: 'Completed',
    totalChapters: 98,
    totalViews: 890000,
    showOnHome: true,
    isFeatured: true,
    isTrending: true,
    createdAt: '2024-08-12T10:00:00Z',
    updatedAt: '2025-02-10T12:00:00Z',
  },
  {
    id: 'comic-solo-leveling',
    title: 'Solo Leveling: Ragnarok',
    slug: 'solo-leveling-ragnarok',
    coverImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=800&auto=format&fit=crop',
    bannerImage: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1200&auto=format&fit=crop',
    synopsis: 'Ketika gerbang misterius kembali terbuka dan ancaman Itarim mengintai bumi, Sung Su-Ho, putra dari Shadow Monarch Sung Jin-Woo, membangkitkan kekuatan terpendamnya.',
    storyWriter: 'Chugong / Daul',
    artist: 'Redice Studio',
    rating: 4.92,
    ratingCount: 54100,
    genres: ['Action', 'Fantasy', 'Monsters', 'System', 'Adventure'],
    type: 'manhwa',
    contentRating: 'normal',
    status: 'Ongoing',
    totalChapters: 42,
    totalViews: 1200000,
    showOnHome: true,
    isFeatured: true,
    isTrending: true,
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-02-21T09:00:00Z',
  },
  {
    id: 'comic-one-piece',
    title: 'One Piece',
    slug: 'one-piece',
    coverImage: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=800&auto=format&fit=crop',
    synopsis: 'Monkey D. Luffy menolak membiarkan siapapun menghalangi mimpinya menjadi Raja Bajak Laut. Bersama kru Topi Jerami, mereka mengarungi Grand Line mencari harta karun legendaris One Piece.',
    storyWriter: 'Eiichiro Oda',
    artist: 'Eiichiro Oda',
    rating: 4.98,
    ratingCount: 98700,
    genres: ['Shounen', 'Action', 'Adventure', 'Comedy', 'Super Power'],
    type: 'manga',
    contentRating: 'normal',
    status: 'Ongoing',
    totalChapters: 1130,
    totalViews: 3500000,
    showOnHome: true,
    isFeatured: false,
    isTrending: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-02-20T16:00:00Z',
  },
  {
    id: 'comic-martial-peak',
    title: 'Martial Peak (Puncak Bela Diri)',
    slug: 'martial-peak',
    coverImage: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?q=80&w=800&auto=format&fit=crop',
    synopsis: 'Perjalanan menuju puncak bela diri adalah jalan yang sepi dan berbahaya. Yang Kai, seorang penyapu lantai paviliun bela diri, menemukan Kitab Hitam tanpa kata yang mengubah takdirnya selamanya.',
    storyWriter: 'Momo',
    artist: 'Pikapi',
    rating: 4.75,
    ratingCount: 33400,
    genres: ['Martial Arts', 'Cultivation', 'Action', 'Harem', 'Fantasy'],
    type: 'manhua',
    contentRating: 'normal',
    status: 'Ongoing',
    totalChapters: 3600,
    totalViews: 2100000,
    showOnHome: true,
    isFeatured: false,
    isTrending: false,
    createdAt: '2024-05-10T00:00:00Z',
    updatedAt: '2025-02-15T11:00:00Z',
  },
  {
    id: 'comic-nano-machine',
    title: 'Nano Machine',
    slug: 'nano-machine',
    coverImage: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?q=80&w=800&auto=format&fit=crop',
    synopsis: 'Cheon Yeo-Woon, seorang pangeran terkucil dari Sekte Iblis, disuntikkan mesin nano berteknologi masa depan oleh keturunannya yang datang dari masa depan.',
    storyWriter: 'Hanjung Wolya',
    artist: 'Geum Gangbulgoe',
    rating: 4.88,
    ratingCount: 42100,
    genres: ['Action', 'Murim', 'Sci-Fi', 'Revenge', 'Overpowered'],
    type: 'manhwa',
    contentRating: 'normal',
    status: 'Ongoing',
    totalChapters: 210,
    totalViews: 1450000,
    showOnHome: true,
    isFeatured: false,
    isTrending: true,
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2025-02-19T14:00:00Z',
  }
];

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'user-admin',
    username: 'admin',
    password: 'admin123@password',
    role: 'admin',
    status: 'active',
    planType: 'plan_15k_all',
    accessType: 'all',
    allowedComicIds: [],
    createdAt: '2025-01-01T00:00:00Z',
    notes: 'Super Admin Sistem',
  },
  {
    id: 'user-reader-5k',
    username: 'andi_5k',
    password: 'reader123',
    role: 'reader',
    status: 'active',
    planType: 'plan_5k_single',
    accessType: 'specific',
    // Hanya boleh membaca 1 komik 18+ yang dipilih admin: Secret Stepmother
    allowedComicIds: ['comic-secret-stepmother'],
    expiresAt: '2026-12-31T23:59:59Z',
    createdAt: '2025-02-01T10:00:00Z',
    notes: 'Paket Rp 5.000 (Khusus Secret Stepmother)',
  },
  {
    id: 'user-reader-15k',
    username: 'budi_vip',
    password: 'reader123',
    role: 'reader',
    status: 'active',
    planType: 'plan_15k_all',
    accessType: 'all',
    allowedComicIds: [],
    expiresAt: '2026-12-31T23:59:59Z',
    createdAt: '2025-02-10T12:00:00Z',
    notes: 'Paket Rp 15.000 VIP (Akses Semua Komik 18+)',
  }
];

export const INITIAL_COMMENTS: CommentItem[] = [
  {
    id: 'comment-1',
    comicId: 'comic-secret-stepmother',
    userId: 'google-user-1',
    userName: 'Rian Santoso',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rian',
    isGoogleUser: true,
    content: 'Artnya juara banget! Penulis Kim Min-Woo & artist Park Jin-Ah emang kolaborasi terbaik!',
    isSpoiler: false,
    likes: 24,
    likedBy: [],
    createdAt: '2025-02-19T14:32:00Z',
  },
  {
    id: 'comment-2',
    comicId: 'comic-secret-stepmother',
    userId: 'google-user-2',
    userName: 'Dewi Lestari',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dewi',
    isGoogleUser: true,
    content: 'Plot twist di chapter 40 bener-bener bikin kaget, jangan sampai kelewatan!',
    isSpoiler: true,
    likes: 12,
    likedBy: [],
    createdAt: '2025-02-20T08:15:00Z',
  },
  {
    id: 'comment-3',
    comicId: 'comic-solo-leveling',
    userId: 'google-user-3',
    userName: 'Aris Wicaksono',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aris',
    isGoogleUser: true,
    content: 'Solo Leveling Ragnarok makin seru, aura Suho beneran mirip Jin-Woo!',
    isSpoiler: false,
    likes: 45,
    likedBy: [],
    createdAt: '2025-02-21T06:40:00Z',
  }
];
